### PR TITLE
Tidying up landr pages

### PR DESCRIPTION
**Pull request by Bucknalla**
Change-type: patch
Signed-off-by: Alex Bucknall <alex.bucknall@gmail.com>

### CODE REVIEW

**Comment by curcuz** [comment]
@Bucknalla do you need review on this? looks like it could be merged to me

**Comment by Bucknalla** [comment]
@curcuz I was mostly just testing the bot out seeing how it looks; I'm going to do a squash and a clean up then I'll let you know when its ready :)

**Comment by Bucknalla** [comment]
@balena-ci rebase

**Comment by Bucknalla** [comment]
@balena-ci I self-certify!

**Pull request merged**
